name: 'diligence-fuzzing'
description: 'run diligence fuzzing cli'
author: 'Diligence'
branding:
  icon: 'bar-chart-2'
  color: 'white'

inputs:
  checkout:
    description: 'Flag to control if the action should check out your repository using actions/checkout@v3.'
    required: false
    default: 'true'
  install_foundry:
    description: 'Flag to control if the action should install Foundry using foundry-rs/foundry-toolchain@v1.'
    required: false
    default: 'true'
  fuzz_api_key:
    description: 'The API key used to submit campaigns to the Diligence Fuzzing API. '
    required: true
  fuzz_project:
    required: false
    description: 'The name of the project to add submitted campaigns to.'
    default: ${{ github.repository }}
  fuzz_time_limit:
    required: false
    description: 'The time limit for each individual fuzzing job (e.g., 10m, 1h, 30s).'
    default: '1h'

runs:
  using: "composite"
  steps:
  - name: Checkout (if needed)
    if: ${{ inputs.checkout == 'true' }}
    uses: actions/checkout@v3

  - name: Install Foundry
    if: ${{ inputs.install_foundry == 'true' }}
    uses: foundry-rs/foundry-toolchain@v1

  - name: Install diligence fuzzing
    run: pip3 install diligence-fuzzing
    shell: bash

  - name: Run fuzz foundry
    env:
      FUZZ_API_KEY: ${{ inputs.fuzz_api_key }}
      FUZZ_PROJECT: ${{ inputs.fuzz_project }}
      FUZZ_TIME_LIMIT: ${{ inputs.fuzz_time_limit }}
    run: fuzz forge test
    shell: bash
